export const glanceAwayPrivacyHtml = `
<h3 class="wp-block-heading"><strong>Privacy Policy for GlanceAway</strong></h3>

<h5 class="wp-block-heading"><strong>Effective Date: August 5, 2026</strong></h5>
<h5 class="wp-block-heading"><strong>Version: 1.3</strong></h5>

<h5 class="wp-block-heading"><strong>Controller</strong></h5>
<p>Georgios Andi Avenidis<br>Berliner Strasse 235<br>65205 Wiesbaden, Germany<br>Email: <a href="mailto:info@georgevalandis.com">info@georgevalandis.com</a></p>

<h5 class="wp-block-heading"><strong>1. Introduction</strong></h5>
<p>This Privacy Policy applies to the GlanceAway app developed by Georgios Andi Avenidis. GlanceAway helps users take screen breaks, customize timer intervals, receive reminders, and review simple progress statistics.</p>
<p>The app is designed around local-first tracking. Your timer settings, break routine, session history, statistics, and preferences remain on your device and are not sent to George Valandis servers.</p>

<h5 class="wp-block-heading"><strong>2. Data Stored on Your Device</strong></h5>
<p>GlanceAway may store timer settings, work and break intervals, reminder and notification preferences, onboarding and premium state, session history, completed break counts, streaks, statistics, and technical app state locally on your device.</p>
<p>This information is used to provide the app's timer, break overlay, reminder, statistics, onboarding, paywall, and settings features.</p>

<h5 class="wp-block-heading"><strong>3. Purchases and Third-Party Services</strong></h5>
<p>If you buy or restore premium access, Apple processes the payment through the App Store. GlanceAway uses RevenueCat to validate purchases, restore access, and unlock premium features.</p>
<p>Apple and RevenueCat may process technical purchase and entitlement information, such as product identifiers, purchase or restore status, receipt-related validation data, an anonymous app user identifier, device and app metadata required for purchase validation, and entitlement state.</p>
<p>GlanceAway does not send your timer settings, session history, break statistics, reminder preferences, or routine data to RevenueCat. Purchase validation data is not used for advertising or cross-app tracking.</p>

<h5 class="wp-block-heading"><strong>4. Product Analytics and Diagnostics</strong></h5>
<p>GlanceAway includes a privacy-focused analytics layer to help test and improve product flows, especially where users may get stuck, where purchases are attempted, and where review prompts are shown.</p>
<p>When external analytics is enabled in a release build, GlanceAway may send limited product interaction events to TelemetryDeck GmbH. Events may include app lifecycle events; timer, break overlay, statistics, settings, onboarding, paywall, purchase, and restore actions; and review prompt eligibility, request, or suppression.</p>
<p>The analytics payload is limited to sanitized event names, short event parameters, app version, build number, locale, operating system, platform, timestamps, and similar technical context. TelemetryDeck may also process an app-installation or device identifier generated by its SDK and session-related identifiers for analytics.</p>
<p>GlanceAway does not send your timer settings, session history, break statistics, reminder contents, screen contents from other apps, names, email addresses, precise location, or advertising identifiers to TelemetryDeck. It does not set a custom TelemetryDeck user ID based on your email address or name.</p>
<p>These analytics are used only to understand product usage, diagnose drop-off points, and improve GlanceAway. The app does not use third-party advertising SDKs and is not designed to track you across apps, websites, or services for advertising purposes.</p>

<h5 class="wp-block-heading"><strong>5. Optional Anonymous Feedback Survey</strong></h5>
<p>After you cancel an active timer session, GlanceAway may offer a short, optional feedback survey hosted by Tally BV. The survey asks what you wanted to achieve and what made you stop the session.</p>
<p>GlanceAway does not send your name, email address, account information, device identifier, timer settings, or session history to the survey. The app does not add hidden user identifiers to the survey link. You can answer without providing contact information, and choosing not to participate does not affect the app.</p>
<p>If you open or submit the survey, Tally processes the answers you provide, a Tally-generated respondent identifier, and technical connection data needed to deliver its website, such as browser information and timestamps, under <a href="https://tally.so/help/privacy-policy" target="_blank" rel="noopener noreferrer">Tally's privacy policy</a>. Survey answers are used only to understand why sessions are cancelled and to improve GlanceAway. Responses are retained for up to 12 months and then deleted, unless they are no longer needed and deleted sooner or must be retained for a legal reason.</p>
<p>You can withdraw consent before submitting by closing the survey. After submission, you may contact <a href="mailto:info@georgevalandis.com">info@georgevalandis.com</a> to request access or deletion. Because the survey does not ask for contact information, an individual response can only be located if you provide enough information to identify it without identifying another respondent's response.</p>
<p>GlanceAway may record whether the survey invitation was shown, accepted, or dismissed through the product analytics described above. It does not send survey answers to TelemetryDeck.</p>

<h5 class="wp-block-heading"><strong>6. Notifications and Optional Permissions</strong></h5>
<p>If you enable reminders or notifications, GlanceAway may use local device notification features to remind you to take screen breaks. You can disable notifications at any time in the app or operating system settings.</p>
<p>If a feature asks for an optional device permission, the permission is used only for the feature described at the time of the request. You can withdraw permissions in system settings.</p>

<h5 class="wp-block-heading"><strong>7. Data Transfer and Storage</strong></h5>
<p>Core timer and statistics data remains on your device. GlanceAway does not operate its own server for your timer settings, break routine, session history, statistics, or preferences. No cloud sync is enabled by default.</p>
<p>Platform-managed backups, such as iCloud device backups, may include local app data depending on your device and account settings.</p>

<h5 class="wp-block-heading"><strong>8. Data Deletion</strong></h5>
<p>You can reset or change app data where the app provides controls for that data. Removing GlanceAway from your device deletes locally stored app data from that device. Platform-managed backups may retain copies according to your Apple account and device backup settings.</p>

<h5 class="wp-block-heading"><strong>9. User Rights</strong></h5>
<p>Depending on applicable law, you may have rights to access, correct, delete, restrict, or object to processing of personal data. Because core app data is stored locally, most control is exercised directly in the app or by deleting the app. The privacy practices and request processes of Apple, RevenueCat, Tally, or TelemetryDeck may also apply to data they process.</p>

<h5 class="wp-block-heading"><strong>10. Security</strong></h5>
<p>GlanceAway keeps core timer and statistics data on your device. You should protect your device with a passcode, biometric authentication, and current operating system updates. GlanceAway does not use automated decision-making or profiling for legal or similarly significant effects.</p>

<h5 class="wp-block-heading"><strong>11. Cookies and Tracking Technologies</strong></h5>
<p>The mobile app does not use website cookies. The optional survey opens a Tally-hosted website, where Tally's own privacy and technical delivery practices apply. GlanceAway is not designed to use advertising trackers or cross-app tracking technologies.</p>

<h5 class="wp-block-heading"><strong>12. Children</strong></h5>
<p>GlanceAway is not directed to children under the age of 13. The app does not require an account and is not designed to collect personal data from children. Parents or guardians should supervise children's app use where appropriate.</p>

<h5 class="wp-block-heading"><strong>13. Changes to This Privacy Policy</strong></h5>
<p>This policy may be updated when the app, third-party services, or legal requirements change. The effective date and version number above show the current version. The latest version is published in the app and on the website.</p>

<h5 class="wp-block-heading"><strong>14. Contact</strong></h5>
<p>If you have questions about privacy or this policy, contact <a href="mailto:info@georgevalandis.com">info@georgevalandis.com</a>.</p>
`;
